### ISSUE TITLE
Create Schematic

### ISSUE THREAD

**Issue by benjigifford** [LilPest0/CCC410F22#11]
Create a logical diagram depicting how the parts will be wired

![image](https://github.com/LilPest0/CCC410F22/assets/90120192/f4a561cf-7ece-4c36-b3f4-efe7c9e4bda2)

**Comment by LilPest0** [comment]
- [ ] Create model in CAD or find one already made
- [ ] Choose appropriate material for printing (PLA, ABS, PETG etc.)
- [ ] Print case at the Generator makerspace
